### ISSUE TITLE
Error is null when channel is not found

### ISSUE THREAD

**Issue by dylannz** [jbueza/node-twitchtv#10]
When calling twitch.channels with an invalid channel username, it returns "status: 404" in the response:

```
response:  { error: 'Not Found',
  status: 404,
  message: 'Channel \'s1mpleofsdsddsd\' does not exist' }
```

Yet the 'error' argument is null:

```err: null```

Error should contain some kind of non-null value, or else it's a useless arg.

**Comment by jbueza** [comment]
Thanks @dylannz for putting this issue up -- and thank you for addressing it in the related pull request. :+1:  :+1:
