### ISSUE TITLE
Is a password necessary for the api?

### ISSUE THREAD

**Issue by Cleanse** [jbueza/node-twitchtv#9]
I come from the PHP side of things and a password is not needed:

$res = $client->get('https://api.twitch.tv/kraken/streams/' . $name,
            ['headers' => ['Client-ID' => env('TWITCH_ID')]]
        );

Is there another reason username and password are requested in your package?

**Comment by jbueza** [comment]
@Cleanse I don't believe it is required anymore (their API has been updated!)

**Comment by Cleanse** [comment]
I see it _can_ be required if you wish to auth users. Working on stuff, might submit a pull request.

**Comment by jbueza** [comment]
Sounds good @Cleanse  -- Hugely appreciate your initiative and effort!

Cheers,
Jaime
